"""Report writing and Telegram notifications."""
from __future__ import annotations

import os
import re
from datetime import datetime, timezone
from typing import Any

from server_agent._models import GuardianRun, HealAction, Severity


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _reports_dir() -> str:
    d = os.environ.get("REPORTS_DIR", "/tmp/server-agent/reports")
    os.makedirs(d, exist_ok=True)
    return d


def _day_dir(reports_dir: str, date: datetime | None = None) -> str:
    d = date or _now_utc()
    day = os.path.join(reports_dir, d.strftime("%Y-%m-%d"))
    os.makedirs(day, exist_ok=True)
    return day


def _severity_emoji(severity: Severity | None) -> str:
    if severity == Severity.CRITICAL:
        return "🔴"
    if severity == Severity.WARNING:
        return "🟡"
    return "🟢"


def write_incident_report(run: GuardianRun, container_name: str) -> str:
    """Write a single container incident report. Returns file path."""
    reports_dir = _reports_dir()
    day_dir = _day_dir(reports_dir)
    ts = run.timestamp.strftime("%H-%M")
    filename = f"{ts}-incident-{container_name.replace('/', '-')}.md"
    path = os.path.join(day_dir, filename)

    container = next((c for c in run.containers if c.name == container_name), None)
    actions = [a for a in run.actions if a.container == container_name]
    severity = container.max_severity if container else Severity.INFO
    status = "RESOLVED" if any(a.success for a in actions) else "ESCALATED" if any(a.escalated for a in actions) else "DETECTED"

    lines = [
        f"# Incident Report — {container_name}",
        "",
        f"**Date:** {run.timestamp.strftime('%Y-%m-%d %H:%M')} UTC",
        f"**Severity:** {severity.value if severity else 'INFO'}",
        f"**Container:** {container_name}",
        f"**Status:** {status}",
        "",
        "---",
        "",
        "## Anomalies",
        "",
    ]

    if container and container.anomalies:
        lines.append("| Type | Severity | Detail |")
        lines.append("|------|----------|--------|")
        for a in container.anomalies:
            lines.append(f"| {a.type} | {_severity_emoji(a.severity)} {a.severity.value} | {a.detail} |")
    else:
        lines.append("No anomalies recorded.")

    lines += ["", "## Actions Taken", ""]
    if actions:
        for a in actions:
            icon = "✅" if a.success else "⚠️" if a.escalated else "❌"
            lines.append(f"- {icon} `{a.command}` — {a.result or a.escalation_reason or 'no result'}")
    else:
        lines.append("No actions taken.")

    if container:
        lines += [
            "",
            "## Container State at Detection",
            "",
            f"- **Image:** `{container.image}`",
            f"- **Status:** `{container.status}`",
            f"- **Restart count:** {container.restart_count}",
            f"- **Memory:** {container.memory_pct:.1f}%",
            f"- **CPU:** {container.cpu_pct:.1f}%",
        ]

    lines += ["", "---", f"*Generated by server-agent at {run.timestamp.isoformat()}*", ""]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    return path


def write_security_report(run: GuardianRun) -> str:
    """Write a security scan report. Returns file path."""
    reports_dir = _reports_dir()
    day_dir = _day_dir(reports_dir)
    ts = run.timestamp.strftime("%H-%M")
    path = os.path.join(day_dir, f"{ts}-security-scan.md")

    critical = [f for f in run.security if f.severity == Severity.CRITICAL]
    warnings = [f for f in run.security if f.severity == Severity.WARNING]

    lines = [
        "# Security Scan Report",
        "",
        f"**Date:** {run.timestamp.strftime('%Y-%m-%d %H:%M')} UTC",
        f"**Scope:** {run.scope}",
        f"**Status:** {'FINDINGS' if run.security else 'CLEAN'}",
        "",
        "---",
        "",
        f"## Summary: {len(critical)} CRITICAL, {len(warnings)} WARNING",
        "",
    ]

    if not run.security:
        lines.append("✅ No security findings.")
    else:
        by_type: dict[str, list[Any]] = {}
        for f in run.security:
            by_type.setdefault(f.type, []).append(f)

        for ftype, findings in by_type.items():
            lines += [f"### {ftype.replace('_', ' ').title()}", ""]
            lines.append("| Severity | Target | Detail |")
            lines.append("|----------|--------|--------|")
            for f in findings:
                lines.append(
                    f"| {_severity_emoji(f.severity)} {f.severity.value} | `{f.target}` | {f.detail} |"
                )
            lines.append("")

    lines += ["---", f"*Generated by server-agent at {run.timestamp.isoformat()}*", ""]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    return path


def write_daily_summary(runs: list[GuardianRun], date: datetime | None = None) -> str:
    """Write a daily summary report aggregating all runs. Returns file path."""
    reports_dir = _reports_dir()
    day_dir = _day_dir(reports_dir, date)
    path = os.path.join(day_dir, "daily-summary.md")

    d = (date or _now_utc()).strftime("%Y-%m-%d")
    total_runs = len(runs)
    total_incidents = sum(len(r.unhealthy_containers) for r in runs)
    total_actions = sum(len([a for a in r.actions if a.success]) for r in runs)
    total_escalated = sum(len([a for a in r.actions if a.escalated]) for r in runs)
    security_findings = sum(len(r.security) for r in runs)

    lines = [
        f"# Daily Summary — {d}",
        "",
        f"**Period:** {d} 00:00 → 23:59 UTC",
        f"**Guardian runs:** {total_runs}",
        f"**Incidents detected:** {total_incidents}",
        f"**Actions taken:** {total_actions} auto-resolved, {total_escalated} escalated",
        f"**Security findings:** {security_findings}",
        "",
        "---",
        "",
        "## Incidents",
        "",
    ]

    all_incidents: list[tuple[str, str, str]] = []  # (time, container, severity)
    for r in runs:
        for c in r.unhealthy_containers:
            sev = c.max_severity.value if c.max_severity else "INFO"
            all_incidents.append((r.timestamp.strftime("%H:%M"), c.name, sev))

    if all_incidents:
        lines.append("| Time | Container | Severity |")
        lines.append("|------|-----------|----------|")
        for time, name, sev in all_incidents:
            lines.append(f"| {time} | `{name}` | {sev} |")
    else:
        lines.append("✅ No incidents today.")

    lines += [
        "",
        "## Actions",
        "",
    ]

    all_actions: list[HealAction] = []
    for r in runs:
        all_actions.extend(r.actions)

    if all_actions:
        lines.append("| Container | Action | Result |")
        lines.append("|-----------|--------|--------|")
        for a in all_actions:
            icon = "✅" if a.success else "⚠️" if a.escalated else "❌"
            lines.append(f"| `{a.container}` | `{a.action}` | {icon} {a.result or a.escalation_reason} |")
    else:
        lines.append("No actions were taken today.")

    lines += ["", "---", f"*Generated by server-agent at {_now_utc().isoformat()}*", ""]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    return path


def update_index(reports_dir: str | None = None) -> str:
    """Regenerate the master index.md by scanning all report files."""
    rd = reports_dir or _reports_dir()
    index_path = os.path.join(rd, "index.md")

    lines = [
        "# Server Agent — Report Index",
        "",
        f"Updated: {_now_utc().strftime('%Y-%m-%d %H:%M')} UTC",
        "",
    ]

    # Scan day directories newest first
    day_dirs: list[str] = []
    try:
        for entry in sorted(os.scandir(rd), key=lambda e: e.name, reverse=True):
            if entry.is_dir() and re.match(r"\d{4}-\d{2}-\d{2}", entry.name):
                day_dirs.append(entry.path)
    except Exception:
        pass

    for day_path in day_dirs[:7]:  # last 7 days
        day_name = os.path.basename(day_path)
        lines += [f"## {day_name}", ""]

        files = sorted(
            [f for f in os.listdir(day_path) if f.endswith(".md")],
            reverse=True,
        )
        if files:
            lines.append("| File | Type |")
            lines.append("|------|------|")
            for fname in files:
                ftype = "daily" if "daily" in fname else "security" if "security" in fname else "incident"
                lines.append(f"| [{fname}](./{day_name}/{fname}) | {ftype} |")
        else:
            lines.append("*No reports.*")
        lines.append("")

    with open(index_path, "w") as f:
        f.write("\n".join(lines))

    return index_path


def send_telegram(message: str, level: str = "info") -> bool:
    """Send Telegram notification using tg-notify library if available."""
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")

    if not token or not chat_id:
        return False

    try:
        from tg_notify import send_alert, send_error, send_info, send_success, send_warning

        fn_map = {
            "critical": send_alert,
            "error": send_error,
            "warning": send_warning,
            "success": send_success,
            "info": send_info,
        }
        fn = fn_map.get(level, send_info)
        fn(message)
        return True
    except ImportError:
        # tg-notify not installed — fall back to raw HTTP
        try:
            import urllib.parse
            import urllib.request

            url = f"https://api.telegram.org/bot{token}/sendMessage"
            data = urllib.parse.urlencode({
                "chat_id": chat_id,
                "text": message,
                "disable_web_page_preview": "true",
            }).encode()
            urllib.request.urlopen(url, data=data, timeout=5)
            return True
        except Exception:
            return False


